### ISSUE TITLE
Problems with datasets

### ISSUE THREAD

**Issue by leibny** [navana-tech/baseline_recipe_is21s_indic_asr_challenge#5]
While processing the code-switching data for Hindi-English we found the following issues:

- The segment boundaries are not very good. This unfairly penalizes the Kaldi baseline provided. When scoring by paragraph, instead of by utterance, we get 27.6% WER using a similar setup nearly the same as the Kaldi baseline instead of 36% WER.

- The test set transcriptions include many Hindi words written in English and English words written in Hindi. There should be a GLM file to give participants credit for correctly produced English/Hindi words regardless of the script. We can provide this for the Hindi test set, but the organizers should score the blind test sets in Bengali and Hindi with such a GLM file.

- The transcriptions are fairly noisy and include poorly tokenized text with many removed punctuation marks, such 1004 (1 “point” 0 “point” 0 “point” 4). This is probably found data and it will be hard to systematically fix all such issues, however, it’s not ideal.

- Example of noise in the transcript: 
               * two words are combined and are written as a single word, for example, हैंcolumns, मेंoutlook, हैंsingle, लिखेंthis, आप:थंडरबर्ड, अबsubject, factorand 
               * the same word is written in both Hindi and English: dotडॉट
               * spelling mistakes in the transcripts: shft instead of shift, ड्रॉप=डाउन instead of ड्रॉपडाउन

Is there anybody else aware of these issues?

JHU-CLSP team

**Comment by ajd12342** [comment]
Thank you for raising the issue. A document highlighting this aspect of the challenge was added to the [README](https://github.com/navana-tech/baseline_recipe_is21s_indic_asr_challenge/blob/master/README.md) a couple of weeks ago.
